- name: load distribution-specific variables
  include_vars:
    file: "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_release }}.yml"
  tags: postgresql

- name: import postgresql configuration tasks
  import_tasks: postgresql.yml
  become: yes
  tags: postgresql

- name: import rsnapshot/backup configuration tasks
  import_tasks: backups.yml
  become: yes
  tags:
    - postgresql
    - backup

- name: import rsyslog configuration tasks
  import_tasks: rsyslog.yml
  become: yes
  tags:
    - postgresql
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed | bool


- name: import netdata configuration tasks
  import_tasks: netdata.yml
  become: yes
  tags:
    - postgresql
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: import ansible-facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags: postgresql

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: postgresql

##### UTILITIES #####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- name: import pgmetrics tasks
  import_tasks: utils-pgmetrics.yml
  become: yes
  tags:
    - never
    - utils-pgmetrics
