- include: postgresql.yml
  become: yes
  tags: postgresql

- include: backups.yml
  become: yes
  tags:
    - postgresql
    - backup

- include: netdata.yml
  become: yes
  tags:
    - postgresql
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed|bool

- include: fact.yml
  become: yes
  tags: postgresql

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: postgresql

##### UTILITIES #####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- include: utils-pgmetrics.yml
  become: yes
  tags:
    - never
    - utils-pgmetrics
