- name: install requirements for SSL/TLS certificates generation
  apt:
    state: present
    package:
      - python3-openssl
      - ssl-cert

- name: generate openssl private key
  openssl_privatekey:
    path: "/etc/ssl/private/{{ ldap_account_manager_fqdn }}.key"
  notify: restart apache

- name: generate openssl certificate signing request
  openssl_csr:
    path: "/etc/ssl/private/{{ ldap_account_manager_fqdn }}.csr"
    privatekey_path: "/etc/ssl/private/{{ ldap_account_manager_fqdn }}.key"
    common_name: "{{ ldap_account_manager_fqdn }}"
    key_usage: "digitalSignature,keyEncipherment"
    basicConstraints: "CA:TRUE"
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate self-signed openssl certificate
  openssl_certificate:
    path: "/etc/ssl/certs/{{ ldap_account_manager_fqdn }}.crt"
    privatekey_path: "/etc/ssl/private/{{ ldap_account_manager_fqdn }}.key"
    csr_path: "/etc/ssl/private/{{ ldap_account_manager_fqdn }}.csr"
    provider: selfsigned
  ignore_errors: "{{ ansible_check_mode }}"
  notify: restart apache
