# @tag netdata - setup netdata monitoring system
# @tag netdata-config - copy netdata configuration files
# @tag netdata-modules - setup custom netdata modules
# @tag netdata-needrestart - setup netdata needrestart module
# @tag netdata-logcount - setup netdata logcount module
# @tag netdata-debsecan - setup netdata debsecan module
# @tag utils-autorestart - (manual) reboot hosts if a Linux kernel upgrade is pending

galaxy_info:
  role_name: monitoring_netdata
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Lightweight real-time monitoring and alerting system"
  license: GPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "10"
        - "11"
  galaxy_tags:
    - system
    - performance
    - monitoring
    - alerting
    - health
    - graphs
    - charts
dependencies:
  - nodiscc.xsrv.handlers
