galaxy_info:
  role_name: tt_rss
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Tiny Tiny RSS web-based news feed reader"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
  galaxy_tags:
    - web
    - rss
    - atom
    - news
    - feed
    - reader
dependencies:
  # - nodiscc.xsrv.common # optional
  # - nodiscc.xsrv.backup # optional
  - nodiscc.xsrv.apache
  - nodiscc.xsrv.postgresql
