# @tag tt_rss - setup tt-rss feed reader
# @tag tt_rss-postgresql - setup tt-rss postgresql database
# @tag tt_rss-app - setup tt-rss appllication

galaxy_info:
  role_name: tt_rss
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Tiny Tiny RSS web-based news feed reader"
  license: GPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "10"
        - "11"
  galaxy_tags:
    - web
    - rss
    - atom
    - news
    - feed
    - reader
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common # optional
  # - nodiscc.xsrv.backup # optional
  # - nodiscc.xsrv.postgresql # optional
  # - nodiscc.xsrv.apache # required
