# @tag jitsi - setup jitsi videoconferencing server
# @tag jitsi-users - setup jitsi registered users
# @tag utils-jitsi-listusers - (manual) list jitsi (prosody) registered users

galaxy_info:
  role_name: jitsi
  author: "nodiscc <nodiscc@gmail.com>"
  description: "video conferencing solution"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "12"
  galaxy_tags:
    - jitsi
    - video
    - conference
    - screensharing
    - communication
    - messaging
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common # optional
  # - nodiscc.xsrv.monitoring # optional
  # - nodiscc.xsrv.apache # required in the standard configuration
