galaxy_info:
  role_name: common
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Base setup for Debian servers"
  license: GPL-3.0
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
        - 11
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - hostname
    - kernel
    - networking
    - swap
    - memory
    - sysctl
    - apt
    - debian
    - upgrades
    - pam
    - limits
    - ntp
    - time
    - date
    - ssh
    - firewall
    - fail2ban
    - hardening
    - security
    - utilities
    - users
    - sudo
dependencies: []
