galaxy_info:
  role_name: "common"
  author: "nodiscc"
  description: "Base setup for Debian servers"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 10
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - hostname
    - kernel
    - networking
    - swap
    - memory
    - sysctl
    - apt
    - debian
    - upgrades
    - pam
    - limits
    - ntp
    - time
    - date
    - ssh
    - hardening
    - utilities
    - users
    - sudo
dependencies: []
