- name: include variable checks tasks
  import_tasks: checks.yml
  become: yes
  tags:
    - jellyfin
    - checks
    - jellyfin-opensubtitles-plugin

- name: include jellyfin configuration tasks
  import_tasks: jellyfin.yml
  become: yes
  tags: jellyfin

- name: include jellyfin opensubtitles plugin configuration tasks
  import_tasks: jellyfin-opensubtitles-plugin.yml
  become: yes
  tags:
    - jellyfin
    - jellyfin-opensubtitles-plugin
  when: jellyfin_setup_opensubtitles_plugin | bool

- name: include jellyfin samba share configuration tasks
  import_tasks: samba.yml
  become: yes
  tags:
    - jellyfin
    - samba
  when:
    - jellyfin_samba_share_enabled | bool
    - ansible_local.samba.ansible_managed is defined
    - ansible_local.samba.ansible_managed | bool

- name: include self-signed certificates configuration tasks
  import_tasks: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - jellyfin
  when: jellyfin_https_mode == 'selfsigned'

- name: include apache configuration tasks
  import_tasks: apache.yml
  become: yes
  tags:
    - jellyfin
    - apache

- name: include fail2ban configuration tasks
  import_tasks: fail2ban.yml
  become: yes
  tags:
    - jellyfin
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: include rsnapshot/backup configuration tasks
  import_tasks: backups.yml
  become: yes
  tags:
    - jellyfin
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed | bool

- name: include netdata configuration tasks
  import_tasks: netdata.yml
  become: yes
  tags:
    - jellyfin
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags: jellyfin

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: jellyfin
