- include: checks.yml
  become: yes
  tags:
    - jellyfin
    - checks

- include: jellyfin.yml
  become: yes
  tags: jellyfin

- include: samba.yml
  become: yes
  tags:
    - jellyfin
    - samba
  when: jellyfin_samba_share_enabled|bool

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - jellyfin
  when: jellyfin_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - jellyfin
    - apache

- include: fail2ban.yml
  become: yes
  tags:
    - jellyfin
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed|bool

- include: backups.yml
  become: yes
  tags:
    - jellyfin
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed|bool

- include: netdata.yml
  become: yes
  tags:
    - jellyfin
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed|bool

- include: fact.yml
  become: yes
  tags: jellyfin

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: jellyfin
