# @tag gitea - setup gitea git service/software forge

galaxy_info:
  role_name: gitea
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Self-hosted Git service/software forge"
  license: GPL-3.0
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - git
    - project
    - development
    - issues
    - wiki
    - vcs
    - web
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common
  # - nodiscc.xsrv.monitoring
  # - nodiscc.xsrv.backup
  - nodiscc.xsrv.apache
  # -  nodiscc.xsrv.postgresql
