##### APACHE MOD_EVASIVE #####

- name: copy mod_evasive configuration
  template:
    src: etc_apache2_conf-available_mod-evasive.conf.j2
    dest: /etc/apache2/conf-available/mod-evasive.conf
    mode: 0644
  when: apache_enable_mod_evasive|bool

- name: enable apache mod_evasive
  command: a2enmod evasive
  args:
    creates: /etc/apache2/mods-enabled/evasive.load
  when: apache_enable_mod_evasive|bool
  notify: restart apache

- name: enable apache mod_evasive configuration
  command: a2enconf mod-evasive
  args:
    creates: /etc/apache2/conf-enabled/mod-evasive.conf
  when: apache_enable_mod_evasive|bool
  notify: reload apache

- name: disable apache mod_evasive
  command: a2dismod evasive
  args:
    removes: /etc/apache2/mods-enabled/evasive.load
  when: not apache_enable_mod_evasive|bool
  notify: restart apache

- name: disable apache mod_evasive configuration
  command: a2disconf mod-evasive|bool
  args:
    removes: /etc/apache2/conf-enabled/mod-evasive.conf
  when: not apache_enable_mod_evasive|bool
  notify: reload apache
