- name: create ansible facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: create apache fact file
  template:
    src: etc_ansible_facts.d_apache.fact.j2
    dest: /etc/ansible/facts.d/apache.fact
    mode: "0644"
  notify: update ansible facts
  ignore_errors: "{{ ansible_check_mode }}"
