- name: import variable checks tasks
  import_tasks: checks.yml
  tags:
    - monitoring
    - grafana
    - checks

- name: import grafana installation tasks
  become: yes
  import_tasks: grafana.yml
  tags:
    - monitoring
    - grafana

- name: import self-signed certificates configuration tasks
  import_tasks: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - monitoring
    - grafana
  when:
    - grafana_https_mode == 'selfsigned'
    - ansible_local.apache.ansible_managed is defined
    - ansible_local.apache.ansible_managed | bool

- name: import apache configuration tasks
  import_tasks: apache.yml
  become: yes
  tags:
    - grafana
    - monitoring
    - apache
  when:
    - ansible_local.apache.ansible_managed is defined
    - ansible_local.apache.ansible_managed | bool

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags: grafana

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: grafana
