# configuration variables for my.example.org
# please set required configuration variables (CHANGEME), and remove variables for roles you don't use

##### CONNECTION
# SSH host/port, if different from my.example.org:22
# ansible_host: "my.example.org"
# ansible_port: 22

##### GITEA - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/gitea/defaults/main.yml
gitea_fqdn: "git.CHANGEME.org"

##### HOMEPAGE - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/homepage/defaults/main.yml
homepage_fqdn: "www.CHANGEME.org"

##### JELLYFIN - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/jellyfin/defaults/main.yml
jellyfin_fqdn: "media.CHANGEME.org"

##### NEXTCLOUD - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/nextcloud/defaults/main.yml
nextcloud_fqdn: "cloud.CHANGEME.org"

##### SHAARLI - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/shaarli/defaults/main.yml
shaarli_fqdn: "links.CHANGEME.org"

##### TRANSMISSION - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/transmission/defaults/main.yml
transmission_fqdn: "torrent.CHANGEME.org"

##### TT-RSS - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/tt_rss/defaults/main.yml
tt_rss_fqdn: "rss.CHANGEME.org"

#### OPENLDAP - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/openldap/defaults/main.yml
openldap_fqdn: "ldap.CHANGEME.org"
openldap_domain: "CHANGEME.org"
openldap_organization: "CHANGEME"
openldap_base_dn: "dc=CHANGEME,dc=org"

##### GRAYLOG - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/graylog/defaults/main.yml
graylog_fqdn: "logs.CHANGEME.org"

##### GOTTY - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/gotty/defaults/main.yml
gotty_fqdn: "tty.CHANGEME.org"
gotty_run_username: "CHANGEME"

##### DNSMASQ - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/dnsmasq/defaults/main.yml
dnsmasq_upstream_servers:
  - 1.1.1.1
  - 1.0.0.1

##### COMMON - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/common/defaults/main.yml


##### SAMBA - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/samba/defaults/main.yml

##### LIBVIRT - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/samba/defaults/libvirt.yml

##### DOVECOT - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/mail_dovecot/defaults/main.yml
dovecot_fqdn: "imap.CHANGEME.org"
dovecot_ldap_uri: "ldap://ldap.CHANGEME.org"
dovecot_ldap_base: "ou=users,dc=CHANGEME,dc=org"
dovecot_ldap_bind_dn: "cn=bind,ou=system,dc=CHANGEME,dc=org"

##### WIREGUARD - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/wireguard/defaults/main.yml
wireguard_server_public_ip: "CHANGEME"

##### JITSI - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/jitsi/defaults/main.yml
jitsi_fqdn: "conference.CHANGEME.org"

##### MATRIX - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/matrix/defaults/main.yml
matrix_synapse_fqdn: "matrix.CHANGEME.org"
matrix_element_fqdn: "chat.CHANGEME.org"

#### GOACCESS - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/monitoring/goaccess/defaults/main.yml
goaccess_fqdn: "goaccess.CHANGEME.org"

#### OWNCAST - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/owncast/defaults/main.yml
owncast_fqdn: "livestream.CHANGEME.org"

##### SEARXNG - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/searxng/defaults/main.yml
searxng_fqdn: "search.CHANGEME.org"

##### STIRLING PDF - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/stirlingpdf/defaults/main.yml
stirlingpdf_fqdn: "pdf.CHANGEME.org"

##### MOODIST - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/moodist/defaults/main.yml
moodist_fqdn: "moodist.CHANGEME.org"

##### KIWIX - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/kiwix/defaults/main.yml
kiwix_fqdn: "kiwix.CHANGEME.org"

##### MONITORING.VICTORIAMETRICS - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/monitoring/victoriametrics/defaults/main.yml
victoriametrics_alertmanager_smtp_host: CHANGEME
victoriametrics_alertmanager_smtp_port: CHANGEME
victoriametrics_alertmanager_smtp_from: "{{ xsrv_admin_email }}"
victoriametrics_alertmanager_email_to: "{{ xsrv_admin_email }}"
