- name: import monitoring utilities installation tasks
  import_tasks: monitoring-utils.yml
  become: yes
  tags:
    - monitoring
    - monitoring_utils

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - monitoring
    - monitoring_utils

##### UTILITIES #####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- name: import duc disk usage analysis tasks
  import_tasks: utils-duc.yml
  become: yes
  tags:
    - never
    - utils-duc

- name: import bonnie++ disk benchmarking tasks
  import_tasks: utils-bonnie.yml
  become: yes
  tags:
    - never
    - utils-bonnie
