- name: install interactive/command-line monitoring tools
  apt:
    state: present
    package:
      - ncdu # ncurses disk usage viewer
      - nethogs # network bandwidth usage monitor
      - htop # system monitor/process manager
      - lsof # list open files
      - strace # trace system calls
      - lnav # enhanced log file viewer
      - iputils-ping # tools to test the reachability of network hosts
      # - spectre-meltdown-checker # spectre & meltdown CPU vulnerability checker
      # - iotop # simple top-like I/O monitor
      # - iftop # displays bandwidth usage information on a network interface
      # - inxi # full featured system information script
      # - arpscan # count machines on LAN
      # - logwatch # log analyser with nice output written in Perl (requires libdate-manip-perl)
