# @tag rocketchat - setup rocketchat communication platform

galaxy_info:
  role_name: rocketchat
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Instant messaging & communication platform"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "11"
  galaxy_tags:
    - chat
    - communication
    - conference
    - instant
    - messaging
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.apache # required
  # - nodiscc.xsrv.docker # required
