galaxy_info:
  role_name: rocketchat
  author: "nodiscc <nodiscc@gmail.com>"
  description: "rocket.chat instant messaging communication platform"
  license: "GPL-3.0"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - chat
    - communication
    - conference
    - instant
    - messaging
dependencies:
  # - nodiscc.xsrv.backup
  - nodiscc.xsrv.apache
  - nodiscc.xsrv.docker
