##### GITEA SELF-HOSTED GIT SERVICE #####
# fully qualified domain name of the gitea instance
gitea_fqdn: "git.CHANGEME.org"
# username/password/e-mail address for the gitea admin user
gitea_admin_username: "CHANGEME"
gitea_admin_password: "CHANGEME"
gitea_admin_email: "CHANGEME"
# 106 character token used for internal API calls authentication
gitea_internal_token: "CHANGEME"
# 64 character global secret key
gitea_secret_key: "CHANGEME"
# 43 character OAuth2 JWT secret
gitea_oauth2_jwt_secret: "CHANGEME"
# 43 character LFS JWT secret
gitea_lfs_jwt_secret: "CHANGEME"
# home directory for the gitea user
gitea_user_home: /var/lib/gitea
# gitea base URL under the domain name (eg change. it to /gitea to serve from https://git.CHANGEME.org/gitea)
gitea_base_url: "/"
# start/stop the gitea service, enable/disable it on boot (yes/no) (redirect users to maintenance page if disabled)
gitea_enable_service: yes
# gitea database settings
gitea_db_type: "postgres" # postgres/mysql
gitea_db_name: "gitea"
gitea_db_user: "gitea"
gitea_db_host: "/run/postgresql/" # /run/postgresql/ for a local postgresql database/peer authentication
gitea_db_password: "" # leave empty for local postgresql database/peer authentication
gitea_db_port: 5432 # usually 5432 for PostgreSQL, 3306 for MySQL
# gitea version to install - https://github.com/go-gitea/gitea/releases.atom; remove leading v
gitea_version: "1.23.7"
# HTTPS and SSL/TLS certificate mode for the gitea webserver virtualhost
#   letsencrypt: acquire a certificate from letsencrypt.org
#   selfsigned: generate a self-signed certificate
gitea_https_mode: selfsigned
# Default visibility setting when creating a new repository (last/private/public)
gitea_default_private: "private"
# force every new repository to be private (true/false - QUOTED)
gitea_force_private: "false"
# User must sign in to view anything (true/false - QUOTED)
gitea_require_signin: "true"
# Disallow registration, only allow admins to create accounts (true/false - QUOTED)
gitea_disable_registration: "true"
# Whether a new user needs to confirm their email when registering (true/false - QUOTED)
gitea_register_email_confirm: "true"
# Whether the email of the user should be shown in the Explore Users page (true/false - QUOTED)
gitea_show_user_email: "false"
# disable all third-party/external services/CDNs (true/false - QUOTED)
gitea_offline_mode: "true"
# disable third-party gravatar service (true/false - QUOTED)
gitea_disable_gravatar: "true"
# global limit of repositories per user, applied at creation time. -1 means no limit
gitea_user_repo_limit: -1
# number of issues that are displayed on one page
gitea_issue_paging_num: 20
# enable/disable gitea REST API (true/false - QUOTED)
gitea_enable_api: "true"
# max number of items in API responses
gitea_api_max_results: 1000
# enable the built-in Gitea Actions CI/CD system (yes/no)
gitea_enable_actions: no
# The minimum password length for new Users
gitea_min_password_length: 10
# comma-separated list of charactacter classes required in passwords (lower,upper,digit,spec or off)
gitea_password_complexity: "lower,upper,digit,spec"
# Allow new users to create organizations by default (true/false - QUOTED)
gitea_default_allow_create_organization: "false"
# yes/no: allow users with git hook privileges to create custom git hooks
# Custom git hooks can be used to perform arbitrary code execution on the host operating system, access and modify files owned by gitea, the database and gain administrator privileges, and access/perform arbitrary actions other resources available to the gitea user on the operating system. Use with caution.
gitea_enable_git_hooks: no
# yes/no: enable/disable the webhooks feature
gitea_enable_webhooks: yes
# list of hosts that can be called from webhooks
# accepts: my.example.org (hostname), *.example.org (wildcards), 192.168.1.0/24 (IP network), loopback (localhost), private (LAN/intranet), external (public hosts on internet), * (all hosts)
gitea_webhook_allowed_hosts:
  - "external"
# port to expose in the clone URL
gitea_ssh_url_port: 22
# enable indexing/searching of repository contents (can consume a lot of system resources)
gitea_repo_indexer_enabled: no
# list of filenames (glob patterns) to exclude from the index. Example:
# gitea_repo_indexer_exclude:
#   - 'resources/bin/**'
#   - '.npm/**'
gitea_repo_indexer_exclude: []
# enable outgoing mail (yes/no)
gitea_mailer_enabled: no
# mail settings below are required if gitea_mailer_enabled: yes
# Mail server protocol (smtp/smtps/smtp+starttls/smtp+unix/sendmail/dummy)
gitea_mail_protocol: "smtp+starttls"
# SMTP mail server address
gitea_mail_host: "{{ msmtp_host | default('smtp.CHANGEME.org') }}"
# SMTP mail server port (e.g. 25/465/587)
gitea_mail_port: "{{ msmtp_port | default('CHANGEME') }}"
# 'From' address used in mails sent by gitea
gitea_mail_from: "{{ msmtp_admin_email | default('gitea-noreply@CHANGEME.org') }}"
# username and password for SMTP authentication
gitea_mail_user: "{{ msmtp_username | default('CHANGEME') }}"
gitea_mail_password: "{{ msmtp_password | default('CHANGEME') }}"
# list of IP addresses allowed to access the gitea web interface (IP or IP/netmask format)
# set to empty list [] to allow access from any IP address
gitea_allowed_hosts: []
