# @tag monitoring - setup monitoring/alerting/logging system/utilities

galaxy_info:
  role_name: monitoring
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Monitoring, alerting, audit and logging system"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
        - 11
  galaxy_tags:
    - system
    - performance
    - monitoring
    - alerting
    - health
    - graphs
    - charts
    - syslog
    - rsyslog
    - logging
    - audit
    - security
dependencies:
  - nodiscc.xsrv.handlers
  - nodiscc.xsrv.monitoring_rsyslog
  - nodiscc.xsrv.monitoring_netdata
  - nodiscc.xsrv.monitoring_utils
