# @tag ollama - setup ollama Large Language Model server
# @tag ollama-ui - setup ollama-ui web interface for ollama

galaxy_info:
  role_name: ollama
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Large Language Model (LLM) runner and web interface"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "12"
  galaxy_tags:
    - llm
    - ai
    - language
    - model
dependencies:
  - nodiscc.xsrv.handlers
