# @tag lynis - setup lynis security audit tool
# @tag monitoring-cli-utils - setup command-line/additional monitoring utilities

galaxy_info:
  role_name: monitoring_utils
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Various monitoring and audit utilities"
  license: GPL-3.0
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
        - 11
  galaxy_tags:
    - system
    - monitoring
    - audit
    - security
dependencies:
  - nodiscc.xsrv.handlers
