galaxy_info:
  role_name: monitoring_utils
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Various monitoring and audit utilities"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
        - 11
  galaxy_tags:
    - system
    - monitoring
    - audit
    - security
dependencies: []
