# enable additional roles by uncommenting them
- hosts: my.example.org
  roles:
    - nodiscc.xsrv.common # base setup
    # - nodiscc.xsrv.monitoring.utils # basic monitoring utilities
    # - nodiscc.xsrv.monitoring.rsyslog # log aggregation, processing and forwarding system
    # - nodiscc.xsrv.monitoring.exporters # monitoring agents/exporters
    # - nodiscc.xsrv.monitoring.victoriametrics # monitoring metrics scraper and time-series database
    # - nodiscc.xsrv.backup # backup service
    # - nodiscc.xsrv.apache # web server + PHP interpreter
    # - nodiscc.xsrv.monitoring.grafana # metrics visualization and analytics application
    # - nodiscc.xsrv.monitoring.goaccess # real-time web log analyzer/interactive viewer
    # - nodiscc.xsrv.openldap # LDAP directory server
    # - nodiscc.xsrv.postgresql # database engine
    # - nodiscc.xsrv.nextcloud # file hosting/sharing/synchronization and collaboration
    # - nodiscc.xsrv.tt_rss # news feed reader
    # - nodiscc.xsrv.shaarli # bookmarking & link sharing
    # - nodiscc.xsrv.podman # OCI container engine
    # - nodiscc.xsrv.gitea # git service/software forge
    # - nodiscc.xsrv.gitea_act_runner # CI/CD runner for gitea actions
    # - nodiscc.xsrv.transmission # bittorrent client
    # - nodiscc.xsrv.mumble # VoIP/voice chat server
    # - nodiscc.xsrv.matrix # real-time secure communication server and web client
    # - nodiscc.xsrv.jellyfin # media server
    # - nodiscc.xsrv.jitsi # video conferencing solution
    # - nodiscc.xsrv.samba # file sharing server
    # - nodiscc.xsrv.dnsmasq # lightweight DNS server
    # - nodiscc.xsrv.wireguard # fast and modern VPN server
    # - nodiscc.xsrv.mail_dovecot # IMAP mailbox server
    # - nodiscc.xsrv.gotty # access server terminal as a web application
    # - nodiscc.xsrv.libvirt # libvirt virtualization toolkit
    # - nodiscc.xsrv.graylog # log management, capture and analysis platform
    # - nodiscc.xsrv.owncast # live video streaming and chat server
    # - nodiscc.xsrv.searxng # metasearch engine
    # - nodiscc.xsrv.stirlingpdf # PDF manipulation tools
    # - nodiscc.xsrv.kiwix # offline wiki viewer
    # - nodiscc.xsrv.ollama # Large Language Model (LLM) runner
    # - nodiscc.xsrv.homepage # simple webserver homepage
