
- hosts: my.example.org
  roles:
    - common
    - backup
    - monitoring
    # - apache
    # - openldap
    # - homepage
    # - mariadb
    # - postgresql
    # - nextcloud
    # - tt_rss
    # - shaarli
    # - gitea
    # - transmission
    # - mumble
    # - docker
    # - rocketchat
    # - jellyfin
    # - samba
