galaxy_info:
  role_name: homepage
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Simple webserver homepage/dashboard"
  license: "GPL-3.0"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - web
    - apache
    - homepage
    - dashboard
dependencies:
  - nodiscc.xsrv.apache
