- include: checks.yml
  tags:
    - nextcloud
    - checks

- include: mysql.yml
  become: yes
  tags: nextcloud
  when: nextcloud_db_type == 'mysql'

- include: postgresql.yml
  become: yes
  tags: nextcloud
  when: nextcloud_db_type == 'pgsql'

- include: nextcloud.yml
  become: yes
  tags: nextcloud

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - nextcloud
  when: nextcloud_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - nextcloud
    - apache

- include: backups.yml
  become: yes
  tags:
    - nextcloud
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed|bool

- include: fail2ban.yml
  become: yes
  tags:
    - nextcloud
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed|bool

- include: rsyslog.yml
  become: yes
  tags:
    - nextcloud
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed|bool

- include: netdata.yml
  become: yes
  tags:
    - nextcloud
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed|bool

- include: fact.yml
  become: yes
  tags: nextcloud

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: nextcloud
