- name: include variable checks tasks
  import_tasks: checks.yml
  tags:
    - victoriametrics
    - monitoring
    - checks

- name: import self-signed certificates configuration tasks
  import_tasks: ssl-selfsigned.yml
  become: yes
  tags:
    - victoriametrics
    - monitoring
    - ssl

- name: import victoriametrics installation tasks
  become: yes
  import_tasks: victoriametrics.yml
  tags:
    - victoriametrics
    - monitoring

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags:
    - victoriametrics
    - monitoring
