# @tag backup - setup rsnapshot backup utility
# @tag rsnapshot-ssh-key - generate ssh key for rsnapshot backup utility

galaxy_info:
  role_name: backup
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Remote/local backup service (rsnapshot)"
  license: GPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "9"
        - "10"
        - "11"
        - "12"
  galaxy_tags:
    - backup
    - incremental
    - rsnapshot
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common # optional
  # - nodiscc.xsrv.monitoring # optional
