- name: import variable checks tasks
  import_tasks: checks.yml
  tags:
    - tt_rss
    - postgresql
    - checks

- name: load distribution-specific variables
  include_vars:
    file: "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_release }}.yml"
  tags:
    - tt_rss
    - apache

- name: import postgresql configuration tasks
  import_tasks: postgresql.yml
  become: yes
  tags:
    - tt_rss
    - postgresql

- name: import tt-rss configuration tasks
  import_tasks: tt-rss.yml
  become: yes
  tags:
    - tt_rss

- name: import self-signed certificates configuration tasks
  import_tasks: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - tt_rss
  when:
    - tt_rss_https_mode == 'selfsigned'
    - ansible_local.apache.ansible_managed is defined
    - ansible_local.apache.ansible_managed | bool

- name: import apache configuration tasks
  import_tasks: apache.yml
  become: yes
  tags:
    - tt_rss
    - apache
  when:
    - ansible_local.apache.ansible_managed is defined
    - ansible_local.apache.ansible_managed | bool

- name: import fail2ban configuration tasks
  import_tasks: fail2ban.yml
  become: yes
  tags:
    - tt_rss
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags: tt_rss

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: tt_rss
