##### TRANSMISSION MONITORING #####

- name: add netdata httpcheck for transmission
  template:
    src: etc_netdata_go.d_httpcheck.conf.d_transmission.conf.j2
    dest: "/etc/netdata/go.d/httpcheck.conf.d/transmission.conf"
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration
