- include: checks.yml
  tags:
    - shaarli
    - checks

- include: shaarli.yml
  become: yes
  tags: shaarli

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - shaarli
  when: shaarli_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - shaarli
    - apache

- include: backups.yml
  become: yes
  tags:
    - shaarli
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed|bool

- include: fail2ban.yml
  become: yes
  tags:
    - shaarli
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed|bool

- include: rsyslog.yml
  become: yes
  tags:
    - shaarli
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed|bool

- include: netdata.yml
  become: yes
  tags:
    - shaarli
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed|bool

- include: fact.yml
  become: yes
  tags: shaarli

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: shaarli
