##### SHAARLI BOOKMARKING SERVICE #####
# Fully Qualified Domain Name for the shaarli instance
shaarli_fqdn: "links.CHANGEME.org"
# Shaarli login and password
shaarli_username: "CHANGEME"
shaarli_password: "CHANGEME"
# 40 character random salt used to hash shaarli password
shaarli_password_salt: "CHANGEME"
# 12 character REST API secret
shaarli_api_secret: "CHANGEME"
# shaarli timezone (see https://www.php.net/manual/en/timezones.php)
shaarli_timezone: "Europe\\/Paris"
# location of the shaarli "home" link
shaarli_header_link: "?"
# hide timestamps (yes/no)
shaarli_hide_timestamps: no
# enable debug log messages (yes/no)
shaarli_debug: no
# shaarli description formatter (default/markdown/markdownExtra)
shaarli_formatter: "markdown"
# enable thumbnails for all hosts, or only common media hosts, or none (all/common/none)
shaarli_thumbnails_mode: 'common'
# overwrite shaarli configuration if it already exists (yes/no - yes will overwrite any changes made from Shaarli tools menu)
shaarli_overwrite_config: no
# Mode for SSL/TLS certificates for the shaarli webserver virtualhost
#   letsencrypt: acquire a certificate from letsencrypt.org
#   selfsigned: generate a self-signed certificate (will generate warning in browsers and clients)
shaarli_https_mode: selfsigned
# Shaarli installation directory
shaarli_install_dir: "/var/www/{{ shaarli_fqdn }}"
# Shaarli version to install - https://github.com/shaarli/Shaarli/releases.atom
shaarli_version: 'v0.12.1'
# php-fpm: Maximum amount of memory a script may consume (K, M, G)
shaarli_php_memory_limit: '128M'
# php_fpm: Maximum execution time of each script (seconds)
shaarli_php_max_execution_time: 30
# php-fpm: Maximum amount of time each script may spend parsing request data (seconds)
shaarli_php_max_input_time: 60
# php-fpm: Maximum size of POST data that PHP will accept (K, M, G)
shaarli_php_post_max_size: '8M'
# php-fpm: Maximum allowed size for uploaded files (K, M, G)
shaarli_php_upload_max_filesize: '2M'
