- name: install rsyslog
  apt:
    state: present
    package:
      - rsyslog
      - rsyslog-gnutls # TLS forwarding support

- name: set retention/rotation policy for rsyslog logs
  template:
    src: etc_logrotate.d_rsyslog.j2
    dest: /etc/logrotate.d/rsyslog
    mode: "0644"

- name: configure rsyslog
  template:
    src: etc_rsyslog.d_{{ item }}.conf.j2
    dest: /etc/rsyslog.d/{{ item }}.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart rsyslog
  with_items:
    - 000-custom # custom configuration
    - 000-singlefile # log all messages to /var/log/syslog
    - 000-imfile # load the imfile (text file input) module used by other roles
    - 000-forwarding # message forwarding over TCP/TLS, if enabled
    - fail2ban # fail2ban logs aggregation
    - apt # apt logs aggregation

- name: configure systemd-journald
  template:
    src: etc_systemd_journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart systemd-journald

# rsyslog is configured to send all messages to /var/log/syslog in singlefile.conf
# if a '*.*' filter is present in main rsyslog.conf, messages will be logged twice
- name: configure rsyslog to avoid duplicate messages
  lineinfile:
    path: /etc/rsyslog.conf
    state: absent
    regexp: '^\*\.\*'
  notify: restart rsyslog
