# @tag gotty - setup gotty web terminal

galaxy_info:
  role_name: gotty
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Share your terminal as a web application"
  license: GPL-3.0
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - shell
    - terminal
    - web
    - commandline
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common # optional
  # - nodiscc.xsrv.monitoring # optional
  # - nodiscc.xsrv.apache # required
