- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that:
      - steamcmd_username is not search("CHANGEME")
      - steamcmd_password is not search("CHANGEME")
      - valheim_server_name is string
      - valheim_server_port == valheim_server_port|int
      - valheim_world_name is string
      - valheim_server_password is not search("CHANGEME")
      - valheim_enable_service == valheim_enable_service|bool
      - valheim_server_firewalld_zones|type_debug == "list"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/valheim_server"
