# automatically create HTTP probes for xsrv roles deployed on these hosts
victoriametrics_auto_check_http_limit: "{{ groups['all'] }}"
# list of URLs to monitor with victoriametrics/blackbox-exporter HTTP probes
# Example:
# victoriametrics_http_checks:
#   - https://prometheus.io
#   - https://www.debian.org
victoriametrics_http_checks: []
# how long to wait before repeating the last notification
victoriametrics_alertmanager_repeat_interval: "1h"
# REQUIRED password to authenticate on exporters when scraping them
victoriametrics_exporters_auth_password: "{{ monitoring_exporters_auth_password }}"
# REQUIRED SMTP host/from address/username/password and recipient address for alertmaneger e-mail alerts
victoriametrics_alertmanager_smtp_host: "{{ msmtp_host | default('smtp.CHANGEME.org') }}"
victoriametrics_alertmanager_smtp_port: "{{ msmtp_port | default('CHANGEME') }}"
victoriametrics_alertmanager_smtp_from: "{{ xsrv_admin_email }}"
victoriametrics_alertmanager_email_to: "{{ xsrv_admin_email }}"
victoriametrics_alertmanager_smtp_auth_username: "{{ msmtp_username | default('CHANGEME') }}"
victoriametrics_alertmanager_smtp_auth_password: "{{ msmtp_password | default('CHANGEME') }}"
# firewall zones from which to allow remote write (zone, state)
# 'zone:' is one of firewalld zones, set 'state:' to 'disabled' to remove the rule
victoriametrics_firewalld_zones:
  - zone: internal
    state: enabled
