# @tag openldap - setup LDAP server
# @tag ldap-account-manager - setup LDAP account manager
# @tag self-service-password - setup LDAP self-service password

galaxy_info:
  role_name: openldap
  author: "nodiscc <nodiscc@gmail.com>"
  description: "LDAP directory server and web management tools"
  license: "GPL-3.0"
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - 10
        - 11
  galaxy_tags:
    - ldap
    - directory
    - authentication
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common # optional
  # - nodiscc.xsrv.monitoring # optional
  # - nodiscc.xsrv.backup # optional
  # - nodiscc.xsrv.apache # required when openldap_setup_lam or openldap_setup_ssp: yes
