- name: install requirements for SSL/TLS certificates generation
  apt:
    state: present
    package:
      - python3-openssl
      - ssl-cert

- name: generate openssl private key
  openssl_privatekey:
    path: "/etc/ssl/private/{{ jitsi_fqdn }}.key"
  notify: restart apache
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate openssl certificate signing request
  openssl_csr:
    path: "/etc/ssl/private/{{ jitsi_fqdn }}.csr"
    privatekey_path: "/etc/ssl/private/{{ jitsi_fqdn }}.key"
    common_name: "{{ jitsi_fqdn }}"
    key_usage: "digitalSignature,keyEncipherment"
    basicConstraints: "CA:TRUE"
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate self-signed openssl certificate
  openssl_certificate:
    path: "/etc/ssl/certs/{{ jitsi_fqdn }}.crt"
    privatekey_path: "/etc/ssl/private/{{ jitsi_fqdn }}.key"
    csr_path: "/etc/ssl/private/{{ jitsi_fqdn }}.csr"
    provider: selfsigned
  notify: restart apache
  ignore_errors: "{{ ansible_check_mode }}"

- name: copy self-signed certificate to system trust store
  copy:
    src: "/etc/ssl/certs/{{ jitsi_fqdn }}.crt"
    dest: "/usr/local/share/ca-certificates/{{ jitsi_fqdn }}.crt"
    remote_src: yes
    mode: 0644
  notify:
    - update CA certificates store
    - restart jitsi
  ignore_errors: "{{ ansible_check_mode }}"
