galaxy_info:
  role_name: mariadb
  author: "nodiscc <nodiscc@gmail.com>"
  description: "MariaDB database engine (community MySQL fork)"
  license: "GPL-3.0"
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - server
    - lamp
    - mariadb
    - mysql
    - database
dependencies: []
#   - nodiscc.xsrv.common
