- name: add rocketchat FQDN to hosts file
  lineinfile:
    path: /etc/hosts
    state: present
    line: "127.0.0.1	{{ rocketchat_fqdn }}" # noqa no-tabs

- name: create directories for rocketchat data
  file:
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0770
    path: "{{ item.path }}"
  with_items:
    - { path: "/var/lib/rocket.chat/db", owner: "999", group: "999" }
    - { path: "/var/lib/rocket.chat/dump", owner: "root", group: "999" }
    - { path: "/var/lib/rocket.chat/uploads", owner: "root", group: "65533" }

- name: copy compose file
  template:
    src: var_lib_rocket.chat_docker-compose.yml.j2
    dest: /var/lib/rocket.chat/docker-compose.yml
    owner: root
    group: root
    mode: 0600

- name: copy mongodb initialization script
  template:
    src: var_lib_rocket.chat_mongo-init.js.j2
    dest: /var/lib/rocket.chat/mongo-init.js
    owner: root
    group: root
    mode: 0644

- name: create/update rocketchat docker stack
  docker_stack:
    name: rocketchat
    prune: yes
    compose: /var/lib/rocket.chat/docker-compose.yml
