# variables in this file apply to all hosts in the 'all' inventory group
# these variables override role defaults
# host-specific variables in host_vars/ override these variables
# dns_nameservers:
#   - "1.1.1.1"
#   - "1.0.0.1"

##### MONITORING.EXPORTERS - https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/monitoring/exporters/defaults/main.yml
monitoring_victoriametrics_url: "http://my.CHANGEME.org:8428"
