# @tag transmission - setup transmission bittorrent client

galaxy_info:
  role_name: transmission
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Transmission Bittorrent client/web interface"
  license: GPL-3.0
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - web
    - bittorrent
    - p2p
    - seedbox
    - download
    - filesharing
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.apache # required
