# @tag graylog - setup graylog log analyzer
# @tag mongodb - setup mongodb database

galaxy_info:
  role_name: graylog
  author: "nodiscc <nodiscc@gmail.com>"
  description: "log aggregation, storage, real-time search and analysis tool"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "11"
        - "12"
  galaxy_tags:
    - logs
    - logging
    - monitoring
    - aggregator
    - syslog
    - analyzer
    - siem
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.monitoring # optional
  # - nodiscc.xsrv.apache # required in the standard configuration
