- name: remove other firewall management tools
  apt:
    package:
      - ufw
      - firewalld
    state: absent
    purge: yes
    autoremove: yes

- name: load nf_conntrack module
  modprobe:
    name: nf_conntrack
    state: present

- name: create firehol configuration directory
  file:
    path: "/etc/firehol"
    state: directory
    mode: 0700

- name: install firehol systemd service
  template:
    src: etc_systemd_system_firehol.service.j2
    dest: /etc/systemd/system/firehol.service
    mode: 0644
  notify: reload systemd unit files

- name: reload systemd unit files (flush handlers)
  meta: flush_handlers

- name: copy firehol configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: restart firewall
  with_items:
    - src: etc_firehol_firehol.conf.j2
      dest: /etc/firehol/firehol.conf
      mode: "0600"
    - src: etc_default_firehol.j2
      dest: /etc/default/firehol
      mode: "0644"

# first firewall startup may cause the SSH connection to hang
- name: install firehol
  apt:
    state: present
    package:
      - firehol
      - firehol-tools
      - ipset
  async: 300
  poll: 5
  when: not ansible_check_mode

- name: start and enable firehol/fail2ban
  service:
    name: "firehol"
    state: started
    enabled: yes

# Apply firewall rules as soon as possible
- name: force all notified handlers to run now
  meta: flush_handlers
