- name: copy sysctl configuration
  template:
    src: 'etc_sysctl.d_custom.conf.j2'
    dest: '/etc/sysctl.d/custom.conf'
    owner: root
    group: root
    mode: "0600"
  notify: apply sysctl configuration

- name: setup kernel modules blacklist
  template:
    src: etc_modprobe.d_blacklist.conf.j2
    dest: /etc/modprobe.d/blacklist.conf
    mode: "0644"
    owner: root
    group: root

- name: configure system to attempt to repair failed filesystems on boot
  template:
    src: etc_default_rcS.j2
    dest: /etc/default/rcS
    owner: root
    group: root
    mode: "0644"

- name: mount /proc
  mount:
    name: /proc
    src: none
    fstype: proc
    opts: "rw,nosuid,nodev,noexec,relatime,hidepid={{ '2' if kernel_proc_hidepid else '0' }}"
    state: mounted

# apply sysctl configuration
- name: apply configuration (flush handlers)
  meta: flush_handlers
