# @tag postgresql - setup postgresql database server

galaxy_info:
  role_name: postgresql
  author: "nodiscc <nodiscc@gmail.com>"
  description: "PostgreSQL database engine"
  license: "GPL-3.0"
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - server
    - lapp
    - postgresql
    - database
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common
  # - nodiscc.xsrv.monitoring
