- include: checks.yml
  tags:
    - graylog
    - checks

- include: requirements.yml
  become: yes
  tags: graylog

- include: mongodb.yml
  become: yes
  tags: graylog

- include: elasticsearch.yml
  become: yes
  tags: graylog

- include: graylog.yml
  become: yes
  tags: graylog

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - graylog
  when: graylog_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - graylog
    - apache

- include: rsyslog.yml
  become: yes
  tags:
    - graylog
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed|bool

- include: netdata.yml
  become: yes
  tags:
    - graylog
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed|bool

- include: fact.yml
  become: yes
  tags: graylog

- include: firewalld.yml
  become: yes
  tags:
    - graylog
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: graylog
