- name: restart grafana
  become: yes
  systemd:
    name: grafana-server.service
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
  when: grafana_enable_service | bool

- name: update CA certificates store
  become: yes
  command: update-ca-certificates
  changed_when: yes
