# @tag apache - setup the apache web server
# @tag ssl - setup SSL certificates and configuration
# @tag apache-reverseproxy - setup apache custom reverseproxies

galaxy_info:
  role_name: apache
  author: "nodiscc <nodiscc@gmail.com>"
  description: "web server/reverse proxy + PHP-FPM interpreter"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "11"
        - "12"
  galaxy_tags:
    - web
    - apache
    - php
    - server
    - webserver
    - reverseproxy
    - lamp
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.monitoring.exporters # optional
