galaxy_info:
  role_name: apache
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Apache web server + PHP-FPM interpreter"
  license: "GPL-3.0"
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 11
  galaxy_tags:
    - web
    - apache
    - php
    - server
    - lamp
dependencies: []
