- name: install interactive/command-line monitoring tools
  apt:
    state: present
    package:
      - ncdu # ncurses disk usage viewer
      - nethogs # network bandwidth usage monitor
      - htop # system monitor/process manager
      - lsof # list open files
      - strace # trace system calls
      - lnav # enhanced log file viewer
      - logwatch
      - libdate-manip-perl
      - iputils-ping # tools to test the reachability of network hosts
      # - spectre-meltdown-checker # Spectre & Meltdown vulnerability/mitigation checker # TODO integrate with lynis
      # - iotop # simple top-like I/O monitor
      # - iftop # displays bandwidth usage information on a network interface
      # - inxi # full featured system information script
      # - arpscan # count machines on LAN

- name: remove default logwatch cron job
  file:
    path: /etc/cron.daily/00logwatch
    state: absent
