##### OPENLDAP DIRECTORY SERVICE #####
# FQDN at which the LDAP server can be reached
openldap_fqdn: "ldap.CHANGEME.org"
# LDAP domain
openldap_domain: "CHANGEME.org"
# LDAP organization
openldap_organization: "CHANGEME"
# LDAP base DN
openldap_base_dn: "dc=CHANGEME,dc=org"
# admin username/password for OpenLDAP server
# the admin DN will be of the form cn=admin,dc=CHANGEME,dc=org
openldap_admin_password: "CHANGEME"
# Unprivilegied "bind" LDAP account username/password
# This account will be allowed to to browse the directory/resolve UIDs and GIDs)
openldap_bind_username: "bind"
openldap_bind_password: "CHANGEME"
# yes/no: start/stop the LDAP server, enable/disable it on boot
openldap_enable_service: yes
# log level for the openldap server (integer) - https://openldap.org/doc/admin24/slapdconf2.html
openldap_log_level: 512
# firewall zones for the LDAP service, if nodiscc.xsrv.common/firewalld role is deployed
# 'zone:' is one of firewalld zones, set 'state:' to 'disabled' to remove the rule (the default is state: enabled)
openldap_firewalld_zones:
  - zone: internal
    state: enabled

##### LDAP ACCOUNT MANAGER #####
# setup LDAP Account Manager web management interface (yes/no)
openldap_setup_lam: yes
# domain name (FQDN) for ldap-account-manager
ldap_account_manager_fqdn: "{{ openldap_fqdn }}"
# comma-separated list of IP addresses allowed to access ldap-account-manager (wildcards allowed)
# for security reasons only private/RFC1918 addresses are allowed by default
ldap_account_manager_allowed_hosts: "10.*,192.168.*,172.16.*,172.17.*,172.18.*,172.19.*,172.20.*,172.21.*,172.22.*,172.23.*,172.24.*,172.25.*,172.26.*,172.27.*,172.28.*,172.29.*,172.30.*,172.31.*"
# installation directory for ldap-account-manager
ldap_account_manager_install_dir: "/var/www/{{ ldap_account_manager_fqdn }}"
# LDAP Account Manager version (https://github.com/LDAPAccountManager/lam/releases)
ldap_account_manager_version: "8.5"
# ldap-account-manager installation method (tar.bz2, apt...)
# currently only tar.bz2 is supported (ldap-account-manager not available in debian 10 repositories)
ldap_account_manager_install_method: "tar.bz2"
# ldap-account-manager session timeout in minutes
ldap_account_manager_session_timeout: 10
# LDAP server URI for ldap-account-manager (e.g. ldap://localhost:389 or ldaps://localhost:636)
ldap_account_manager_ldap_url: "ldap://{{ openldap_fqdn }}:389"
# path to trusted server certificate if using ldaps:// connection (e.g. "certificates/{{ openldap_fqdn }}.openldap.crt" - leave empty to disable)
ldap_account_manager_ldaps_cert: ""
# HTTPS/SSL/TLS certificate mode for the ldap-account-manager webserver virtualhost
#   letsencrypt: acquire a certificate from letsencrypt.org
#   selfsigned: generate a self-signed certificate (will generate warning in browsers and clients)
ldap_account_manager_https_mode: "selfsigned"
# enable/disable the ldap-account-manager php-fpm pool (redirect users to maintenance page if disabled)
ldap_account_manager_enable_service: yes
# php-fpm: Maximum amount of memory a script may consume (K, M, G)
ldap_account_manager_php_memory_limit: '128M'
# php_fpm: Maximum execution time of each script (seconds)
ldap_account_manager_php_max_execution_time: 30
# php-fpm: Maximum amount of time each script may spend parsing request data (seconds)
ldap_account_manager_php_max_input_time: 60
# php-fpm: Maximum size of POST data that PHP will accept (K, M, G)
ldap_account_manager_php_post_max_size: '8M'
# php-fpm: Maximum allowed size for uploaded files (K, M, G)
ldap_account_manager_php_upload_max_filesize: '2M'


##### LDAP SELF SERVICE PASSWORD #####
# setup Self Service Password password change tool (yes/no)
openldap_setup_ssp: no
# domain name (FQDN) for Self Service Password
self_service_password_fqdn: "ssp.CHANGEME.org"
# list of IP addresses/networks allowed to access self service password (CIDR notation)
# for security reasons only private/RFC1918 addresses are allowed by default
# set to empty list [] to allow access from any IP address
self_service_password_allowed_hosts:
  - 10.0.0.0/8
  - 192.168.0.0/16
  - 172.16.0.0/12
# yes/no: enable self service password debug log messages
self_service_password_debug: no
# installation directory for Self Service Password
self_service_password_install_dir: "/var/www/{{ self_service_password_fqdn }}"
# LDAP Self-Service Password version (https://github.com/ltb-project/self-service-password/releases)
self_service_password_version: "1.5.3"
# LDAP server URI for Self Service Password (e.g. ldap://localhost:389 or ldap://ldap.CHANGEME.org:686)
self_service_password_ldap_url: "ldap://{{ openldap_fqdn }}:389"
# HTTPS/SSL/TLS certificate mode for the Self Service Password webserver virtualhost
#   letsencrypt: acquire a certificate from letsencrypt.org
#   selfsigned: generate a self-signed certificate (will generate warning in browsers and clients)
self_service_password_https_mode: "selfsigned"
# enable/disable the self-service-password php-fpm pool (redirect users to maintenance page if disabled)
self_service_password_enable_service: yes
# php-fpm: Maximum amount of memory a script may consume (K, M, G)
self_service_password_php_memory_limit: '64M'
# php_fpm: Maximum execution time of each script (seconds)
self_service_password_php_max_execution_time: 30
# php-fpm: Maximum amount of time each script may spend parsing request data (seconds)
self_service_password_php_max_input_time: 60
# php-fpm: Maximum size of POST data that PHP will accept (K, M, G)
self_service_password_php_post_max_size: '8M'
# php-fpm: Maximum allowed size for uploaded files (K, M, G)
self_service_password_php_upload_max_filesize: '2M'
