- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that: "{{ item }}"
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/wireguard"
  loop:
    - wireguard_server_public_ip == wireguard_server_public_ip | ansible.utils.ipaddr('address')
    - wireguard_enable_service == wireguard_enable_service | bool
    - wireguard_peers | type_debug == 'list'
    - wireguard_firewalld_zones | type_debug == "list"
    - wireguard_firewalld_services | type_debug == "list"
    - wireguard_allow_forwarding == wireguard_allow_forwarding | bool

- name: check that variables are correctly defined (wireguard_peers)
  assert:
    quiet: yes
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/wireguard"
    that:
      - item.name is string
      - item.name is not search('/')
      - ((item.state | default('present') == "present") and (item.ip_address | ansible.utils.ipaddr is not none)) or (item.state == "absent")
      - (item.public_key is not defined) or (item.public_key | b64decode and item.public_key | length == 44)
      - (item.routes is not defined) or (item.routes | type_debug == "list")
  loop: "{{ wireguard_peers }}"

- name: check that variables are correctly defined (wireguard_firewalld_services)
  assert:
    quiet: yes
    fail_msg: "One or more variables are not correctly defined. Check role documentation: https://gitlab.com/nodiscc/xsrv/-/tree/master/roles/wireguard"
    that:
      - item.name is string
      - (item.state is not defined) or (item.state in ['enabled','disabled'])
  loop: "{{ wireguard_firewalld_services }}"
  tags: firewall
