# Fully Qualified Domain Name for the stirlingpdf instance
stirlingpdf_fqdn: "pdf.CHANGEME.org"
# the stirlingpdf OCI image to pull
stirlingpdf_image: "docker.io/frooodle/s-pdf:latest"
# HTTPS and SSL/TLS certificate mode for the stirlingpdf webserver virtualhost
#   letsencrypt: acquire a certificate from letsencrypt.org
#   selfsigned: generate a self-signed certificate
stirlingpdf_https_mode: selfsigned
# start/stop the stirlingpdf service, enable/disable it on boot (yes/no) (redirect users to maintenance page if disabled)
stirlingpdf_enable_service: yes
