# @tag docker - setup docker engine

galaxy_info:
  role_name: docker
  author: "geerlingguy, nodiscc <nodiscc@gmail.com>"
  description: "Open source application containerization technology"
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "10"
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common
  # - nodiscc.xsrv.monitoring
